### ISSUE TITLE
Apprepo-sync jobs never finish

### ISSUE THREAD

**Issue by arapulido** [kubeapps/apprepository-controller#8]
Environment:
* Minikube with RBAC enabled
* Kubernetes version: 1.8.0 
* Kubeapps 0.3.0 branch; 39e0fce5ea014a886e7cf99071bec3da9e8a3b93

After `kubeapps up` I open the dashboard and the list of charts is empty. 

It looks like an RBAC error with the apprepository-controller pod:

https://gist.github.com/arapulido/ef55b57f86d71dc1675ef583975cfa20

**Comment by prydonius** [comment]
@arapulido whilst the controller logs does show a bug in RBAC, from what I can see that's related to the events which are not important to the controller functioning.

From the title of this, there's a deeper issue where the jobs created by the cronjob and initial job are not being completed. Can you paste the output of `kubectl get jobs -n kubeapps` and `kubectl get pods --show-all -n kubeapps`?

**Comment by arapulido** [comment]
The issue was that kube-dns was crashing and the sync jobs couldn't talk to the db. I will close this one (as it is not the real issue) and I have open a new one about logging and failing: https://github.com/kubeapps/apprepository-controller/issues/9
